const RoopenSteroidit = {
  RoopenSteroidit1: {
    "_comment": "",
    "type": "linear",
    "background": "PuhelinMuskelit",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopenSteroidit1",
    "next_scene": "RoopenSteroidit2",
  },
  RoopenSteroidit2: {
    "_comment": "",
    "type": "linear",
    "background": "PuhelinMuskelit",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopenSteroidit2",
    "next_scene": "RoopenSteroidit3",
  },
  RoopenSteroidit3: {
    "_comment": "",
    "type": "options",
    "background": "Steroidit",
    "characters": ["HahmoRoope"],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopenRahapelit",
    "player_choice": [
      {
        "text": "tRoopeSteroidit3Tiedan",
        "next_scene": "RoopePillerit1",
      },
      {
        "text": "tRoopeSteroidit3Mita",
        "next_scene": "SteroiditInfobox1",
      },
    ],
  },
  SteroiditInfobox1: {
    "_comment": "",
    "type": "linear",
    "background": "",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tSteroiditInfobox1",
    "next_scene": "SteroiditInfobox2",
  },
  SteroiditInfobox2: {
    "_comment": "",
    "type": "linear",
    "background": "",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tSteroiditInfobox2",
    "next_scene": "RoopeSteroidit4",
  },
  RoopenSteroidit4: {
    "_comment": "",
    "type": "options",
    "background": "Pillerit",
    "characters": ["HahmoRoope"],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopeSteroidit4",
    "player_choice": [
      {
        "text": "tRoopeSteroidit4Okei",
        "next_scene": "RoopePillerit1",
      },
      {
        "text": "tRoopeSteroidit4IhaSama",
        "next_scene": "RoopePillerit1",
      },
    ],
  },
  RoopePillerit1: {
    "_comment": "",
    "type": "linear",
    "background": "",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopePillerit1",
    "next_scene": "RoopePillerit2",
  },
  RoopenPilleri2: {
    "_comment": "",
    "type": "options",
    "background": "Pillerit",
    "characters": ["HahmoRoope"],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopePillerit2",
    "player_choice": [
      {
        "text": "tRoopePillerit2Ei",
        "next_scene": "RoopePillerit3EiTotta",
      },
      {
        "text": "tRoopePillerit2Joo",
        "next_scene": "RoopePillerit3JooOletkoVarma",
      },
    ],
  },
  RoopePillerit3JooOletkoVarma: {
    "_comment": "Puuttuu nextScene",
    "type": "linear",
    "background": "",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopePillerit3JooOletkoVarma",
    "next_scene": "",
  },
  RoopePillerit3EiTotta: {
    "_comment": "Puuttuu nextScene",
    "type": "linear",
    "background": "",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopePillerit3EiTotta",
    "next_scene": "",
  },
  RoopePillerit3Okei: {
    "_comment": "",
    "type": "linear",
    "background": "",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopePillerit3Okei",
    "next_scene": "RoopeJointti1",
  },
  RoopePillerit3IhaSama: {
    "_comment": "",
    "type": "linear",
    "background": "",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopePillerit3IhaSama",
    "next_scene": "RoopePillerit4",
  },
  RoopePillerit4: {
    "_comment": "",
    "type": "linear",
    "background": "Pillerit",
    "characters": [""],
    "text_type": "speech",
    "text_position": "speechLeft",
    "text": "tRoopePillerit4",
    "next_scene": "RoopeJointti1",
  },
};
export default RoopenSteroidit;
