const RoopenSteroidit = {
  RoopenSteroidit1: {
    _comment: "",
    type: "linear",
    background: "PuhelinMuskelit",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenSteroidit1",
    next_scene: "RoopenSteroidit2",
  },
  RoopenSteroidit2: {
    _comment: "",
    type: "linear",
    background: "PuhelinMuskelit",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenSteroidit2",
    next_scene: "RoopenSteroidit3",
  },
  RoopenSteroidit3: {
    _comment: "",
    type: "options",
    background: "Steroidit",
    characters: ["HahmoRoope"],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenRahapelit",
    player_choice: [
      {
        text: "tRoopenSteroidit3Tiedan",
        next_scene: "RoopenPillerit1",
      },
      {
        text: "tRoopenSteroidit3Mita",
        next_scene: "SteroiditInfobox1",
      },
    ],
  },
  SteroiditInfobox1: {
    _comment: "",
    type: "linear",
    background: "",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tSteroiditInfobox1",
    next_scene: "SteroiditInfobox2",
  },
  SteroiditInfobox2: {
    _comment: "",
    type: "linear",
    background: "",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tSteroiditInfobox2",
    next_scene: "RoopenSteroidit4",
  },
  RoopenSteroidit4: {
    _comment: "",
    type: "options",
    background: "Pillerit",
    characters: ["HahmoRoope"],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenSteroidit4",
    player_choice: [
      {
        text: "tRoopenSteroidit4Okei",
        next_scene: "RoopenPillerit1",
      },
      {
        text: "tRoopenSteroidit4IhaSama",
        next_scene: "RoopenPillerit1",
      },
    ],
  },
  RoopenPillerit1: {
    _comment: "",
    type: "linear",
    background: "",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenPillerit1",
    next_scene: "RoopenPillerit2",
  },
  RoopenPilleri2: {
    _comment: "",
    type: "options",
    background: "Pillerit",
    characters: ["HahmoRoope"],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenPillerit2",
    player_choice: [
      {
        text: "tRoopenPillerit2Ei",
        next_scene: "RoopenPillerit3EiTotta",
      },
      {
        text: "tRoopenPillerit2Joo",
        next_scene: "RoopenPillerit3JooOletkoVarma",
      },
    ],
  },
  RoopenPillerit3JooOletkoVarma: {
    _comment: "Puuttuu nextScene",
    type: "linear",
    background: "",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenPillerit3JooOletkoVarma",
    next_scene: "",
  },
  RoopenPillerit3EiTotta: {
    _comment: "Puuttuu nextScene",
    type: "linear",
    background: "",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenPillerit3EiTotta",
    next_scene: "",
  },
  RoopenPillerit3Okei: {
    _comment: "",
    type: "linear",
    background: "",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenPillerit3Okei",
    next_scene: "RoopenJointti1",
  },
  RoopenPillerit3IhaSama: {
    _comment: "",
    type: "linear",
    background: "",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenPillerit3IhaSama",
    next_scene: "RoopenPillerit4",
  },
  RoopenPillerit4: {
    _comment: "",
    type: "linear",
    background: "Pillerit",
    characters: [""],
    text_type: "speech",
    text_position: "speechLeft",
    text: "tRoopenPillerit4",
    next_scene: "RoopenJointti1",
  },
};
export default RoopenSteroidit;
